### ISSUE TITLE
Keyboard switching issues

### ISSUE THREAD

**Issue by Furiousmikey** [Joexv/FlorkOfStickers#1]
Can use keyboard if you change in settings, but only upon initial use. If I change back to default Samsung keyboard it's impossible to switch to sticker board. Using whatever the current version Android is for s21.

**Comment by Joexv** [comment]
What happens when you bring up the keyboard swap menu? Does it not show the pack or does it crash?

**Comment by Furiousmikey** [comment]
It resolved itself. If anyone else asks, it won't install on the space bar
keyboard switcher. It's accessible via the small keyboard icon located down
by the soft keys.
